<!doctypehtml><html lang="en"><head><meta charset="UTF-8"><meta content="width=device-width,initial-scale=1"name="viewport"><link href="CSS/home.css"rel="stylesheet"><link href="CSS/login.css"rel="stylesheet"><link href="CSS/media.css"rel="stylesheet"><link href="Images/blood logo shortcut.png"rel="shortcut icon"><link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css"rel="stylesheet"crossorigin="anonymous"integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM"><link href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200"rel="stylesheet"><link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css"rel="stylesheet"crossorigin="anonymous"integrity="sha512-z3gLpd7yknf1YoNbCzqRKc4qyor8gaKU1qmn+CShxbuBusANI9QpRohGBreCFkKxLhei6S9CQXFEbbKuqLg0DA=="referrerpolicy="no-referrer"><title>Blood Bank</title></head><body><div class="page"><header><div class="headContainer"><nav class="nav navItem"><ul class="navs"><a href="http://localhost/BloodDonate/index.php"><li>Home</li></a><a href="#contacts"><li>Contact Us</li></a></ul></nav><div class="navItem logo"id="content"><a href="http://localhost/BloodDonate/index.php"><img alt=""src="images/blood logo.png"></a></div></div></header><main><article class="firstMainContainer"><h1>Donors</h1></article><section><table class="table table-hover"><tr class="table-danger"><th>ID</th><th>Donator Name</th><th>Blood Type</th><th>Gender</th><th>Number</th><th>Address</th><th>Time</th>e<th>Edit</th><th>Delete</th></tr><?php $i=1;include("connection.php");$sql=mysqli_query($con,"select * from Donors");while($row=mysqli_fetch_array($sql)){echo"<tr>
                            <td>$i</td>
                            <td>$row[1]</td>
                            <td>$row[2]</td>
                            <td>$row[3]</td>
                            <td>$row[4]</td>
                            <td>$row[5]</td>
                            <td>$row[6]</td>
                            <td>  <a href='update1.php?id=$row[0]'>Edit</a></td>
                            <td><a href='delete1.php?id=$row[0]' onclick='return confirmDelete();'>Delete</a></td>       
                          </tr>";$i++;} ?></table><div class="btn_send"><div class="button_send"><a href="addDonor.php"><i class="fa-plus fa-solid"style="color:#fff"></i> <span class="nav_bar_name"></span></a></div></div></section></main><footer><p>Made By <span>Nada Aldubaie </span>© 2023</p><div class="nav"><ul id="contacts"><a href="https://www.facebook.com/profile.php?id=100080879380127&mibextid=ZbWKwL"class="a_link"><i class="fa-brands fa-square-facebook"></i> </a><a href="https://twitter.com/nadcs0?t=7cyvl_55QEPq0AhlQLwMEQ&s=09"class="a_link"><i class="fa-brands fa-square-twitter"></i> </a><a href="https://www.linkedin.com/in/nada-aldubaie-3a3a96238"class="a_link"><i class="fa-brands fa-linkedin"></i></a></ul></div></footer></div><script>var name=$row[1];function confirmDelete(){return!!confirm("Are you sure you want to delete this donor ?"+name)}</script><script crossorigin="anonymous"integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz"src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script><script crossorigin="anonymous"integrity="sha512-uKQ39gEGiyUJl4AI6L+ekBdGKpGw4xJ55+xyJG7YFlJokPNYegn9KwQ3P8A7aFQAUtUsAQHep+d/lrGqrbPIDQ=="src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/js/all.min.js"referrerpolicy="no-referrer"></script></body></html>