<!doctypehtml><html lang="en"><head><meta charset="UTF-8"><meta content="width=device-width,initial-scale=1"name="viewport"><link href="CSS/home.css"rel="stylesheet"><link href="CSS/media.css"rel="stylesheet"><link href="Images/blood logo shortcut.png"rel="shortcut icon"><link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css"rel="stylesheet"crossorigin="anonymous"integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM"><link href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200"rel="stylesheet"><link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css"rel="stylesheet"crossorigin="anonymous"integrity="sha512-iecdLmaskl7CVkqkXNQ/ZH/XLlvWZOJyj7Yy7tcenmpD1ypASozpmT/E0iPtmFIB46ZmdtAc9eNBvH0H/ZpiBw=="referrerpolicy="no-referrer"><title>Blood Bank</title></head><body><div class="page"><header><div class="headContainer"><nav class="nav navItem"><ul class="navs"><a href="http://localhost/BloodDonate/index.php"><li>Home</li></a><a href="#contacts"><li>Contact Us</li></a></ul><a href="http://localhost/BloodDonate/login.php"><button>Sign in</button></a></nav><div class="navItem logo"id="content"><a href="http://localhost/BloodDonate/index.php"><img alt=""src="images/blood logo.png"></a></div><div class="head_title"><p>Give a hand to people in need</p><p>Click to be a donor now</p><a href="http://localhost/BloodDonate/addDonor.php"><button>Donate</button></a></div></div></header><main><article class="firstMainContainer"><h1>Donors</h1></article><section><div class="boxes"><?php $i=1;include("connection.php");$sql=mysqli_query($con,"SELECT * FROM Donors");while($row=mysqli_fetch_array($sql)){echo"<div class='donor-box'>
                               <div class='box'>

                                        <p>ID: $row[0]</p>
                                        <p>Name: $row[1]</p>
                                        <p>Blood Type: $row[2]</p>
                                        <p>Gender: $row[3]</p>
                                        <p>Number: $row[4]</p>
                                        <p>Address: $row[5]</p>
                                        <p>Time: $row[6]</p>
                                    </div>;
                                    </div>";$i++;} ?></div></div><footer><p>Made By <span>Nada Aldubaie </span>© 2023</p><div class="nav"><ul id="contacts"><a href="https://www.facebook.com/profile.php?id=100080879380127&mibextid=ZbWKwL"class="a_link"><i class="fa-brands fa-square-facebook"></i> </a><a href="https://twitter.com/nadcs0?t=7cyvl_55QEPq0AhlQLwMEQ&s=09"class="a_link"><i class="fa-brands fa-square-twitter"></i> </a><a href="https://www.linkedin.com/in/nada-aldubaie-3a3a96238"class="a_link"><i class="fa-brands fa-linkedin"></i></a></ul></div></footer><script crossorigin="anonymous"integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz"src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script><script crossorigin="anonymous"integrity="sha512-fD9DI5bZwQxOi7MhYWnnNPlvXdp/2Pj3XSTRrFs5FQa4mizyGLnJcN6tuvUS6LbmgN1ut+XGSABKvjN0H6Aoow=="src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/js/all.min.js"referrerpolicy="no-referrer"></script></body></html>